#!/usr/bin/env perl

use strict;
use warnings;
use bytes;


my ($src) = @ARGV;
my $dest = "$src.h";

my $incl_guard = uc($dest =~ s/[.-]/_/gr);
my $identifier = substr($incl_guard, 0, -2);


open my $out, ">", $dest;
select $out;

my $length = 0;

print "#ifndef $incl_guard\n";
print "#define $incl_guard\n";
print "\n";
print "#define $identifier (g_bytes_new_static(\"";

while (<>) {
    $length += length($_);

    $_ =~ s/"/\\"/g;
    $_ =~ s/\n$/\\n/;

    print $_;
}

print "\", $length))\n\n";
print "#endif\n";


select STDOUT;
close $out;
